config/routes.rb
Rails.application.routes.draw do
    
  resources :atypes
  resources :ppis

  authenticated :user do  
    root 'projects#index'   
  end   
    
  unauthenticated do    
    root 'home#index', :as => "unauthenticated"   
  end 
  resources :temp_documents

  resources :revisions

  resources :documents do
    member do
      post 'merge'
      get 'verify'
    end
    resources :ppis
    resources :atypes
  end

  resources :project_users

  resources :projects do 
    resources :documents do
    end
    member do 
      get 'check_same_documents'
    end
    resources :project_users
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'home/index'

end

app/models/document.rb
require 'nokogiri'
class Document < ActiveRecord::Base
  belongs_to :user
  belongs_to :project, counter_cache: true
  has_many :ppis, dependent: :destroy
  has_many :atypes, dependent: :destroy
  paginates_per 20
  TYPE2COLOR = {
    "gene" => "yellow",
    "organism" => "orange",
    "experimentalmethod" => "red",
    "geneticinteractiontype" => "green",
    "gievidence" => "green",
    "gimention" => "green",
    "ppievidence" => "blue",
    "ppimention" => "blue"
  }
  before_save :overwrite_xml

  validate :validate_xml

  def unique_id
    self.doc_id || "D#{self.id}"
  end

  def annotation_types
    types = []
    self.bioc_doc.passages.each do |p|
      p.annotations.each do |a|
        types << a.infons['type'] if !a.infons.nil? && !a.infons['type'].nil?
      end
      p.sentences.each do |s|
        s.annotations.each do |a|
          types << a.infons['type'] if !a.infons.nil? && !a.infons['type'].nil?
        end
      end
    end

    return types.uniq.sort
  end

  def adjust_atypes 
    typemap = {}
    self.atypes.each do |t|
      typemap[t.name] = t
    end
    self.annotation_types.each do |t|
      atype = typemap[t.downcase] 
      if atype.nil?
        self.atypes.create({
          name: t.downcase, document_id: self.id, 
          project_id: self.project_id, cls: Atype.recommend(t.downcase)
        })
      elsif !Atype::CLASSES.include?(atype.cls)
        atype.cls = Atype.recommend(atype.name)
        atype.save
      end
    end
  end

  def atype(name)
    if @atype_map.nil?
      @atype_map = {}
      self.atypes.each do |t|
        @atype_map[t.name] = t
      end
    end
    @atype_map[name]
  end

  def self.create_from_file(file)
    doc = Document.new
    doc.filename = file.original_filename
    if file.respond_to?(:read)
      doc.xml = file.read
    elsif file.respond_to?(:path)
      doc.xml = File.read(file.path)
    else
      logger.error "Bad file: #{file.class.name}: #{file.inspect}"
    end
    begin
      doc.validate_xml
    rescue Exception => e
      logger.error e.inspect
      return nil
    end
    unless doc.bioc.nil?
      doc.source = doc.bioc.source
      doc.d_date = doc.bioc.date
      doc.key = doc.bioc.key
      doc.doc_id = doc.bioc.documents[0].id
    end
    return doc
  end

  def self.create_by_merge(org_doc, xml)
    doc = Document.new
    doc.filename = org_doc.filename 
    doc.xml = org_doc.xml
    doc.source = org_doc.source
    doc.d_date = org_doc.d_date
    doc.key = org_doc.key
    doc.doc_id = org_doc.doc_id
    doc.project_id = org_doc.project_id
    doc.user_id = org_doc.user_id

    # logger.debug(doc.xml)
    # logger.debug("=================")
    # logger.debug(xml)
    dest = SimpleBioC.from_xml_string(doc.xml)
    src = SimpleBioC.from_xml_string(xml)
    SimpleBioC.merge(dest, src)
    doc.xml = SimpleBioC::to_xml(dest)
    return doc
  end

  def merge_with(doc) 
    dest = self.bioc
    src = doc.bioc
    BiocMerger.merge(dest, src)
    self.xml = SimpleBioC::to_xml(dest)
  end
   
  def get_psize(p)
    self.get_ptext(p).size
  end

  def get_ptext(p)
    if p.text.blank?
      p.sentences.map{|s| s.text}.join(" ")
    else
      p.text
    end
  end

  def outline
    root = {children: []}
    last_in_levels = [root]
    last_item = nil
    self.bioc_doc.passages.each_with_index do |p, index|
      next if p.infons["type"].nil?

      result = p.infons["type"].match(/title_(\d+)/)
      if result.present?
        level = result[1].strip.to_i
        item_text = "title"
      elsif %w(front abstract title).include?(p.infons["type"])
        level = 1
        item_text = p.infons["type"]
      else
        if !last_item.nil?
          last_item[:cls] = last_item[:cls] | get_class_from_passage(p)
          next
        end
      end

      desc = self.get_ptext(p)[0..30] 
      item = {id: index, text: item_text, description: desc, children: [], level: level, cls: []}
      
      last_item = item
      last_item[:cls] = last_item[:cls] | get_class_from_passage(p)
      last_in_levels[level] = item
      plevel = level - 1
      while (plevel > 0 && last_in_levels[plevel].nil?) do
        plevel = plevel - 1
      end
      p = last_in_levels[plevel]
      p[:children] << item
    end

    root[:children]
  end

  def article_id_pmc
    if @article_id_pmc.nil?
      @article_id_pmc = self.find_value_for_infonkey("article-id_pmc") 
    end
    return @article_id_pmc
  end

  def article_id_pmid
    if @article_id_pmid.nil?
      @article_id_pmid = self.find_value_for_infonkey("article-id_pmid") 
    end
    return @article_id_pmid
  end

  def find_value_for_infonkey(key)
    return self.bioc_doc.infons[key] unless self.bioc_doc.infons[key].nil?
    self.bioc_doc.passages.each do |p|
      return p.infons[key] unless p.infons[key].nil?
    end
    
  end

  def get_class_from_passage(p)
    cls = []
    p.annotations.each do |a|
      cls = cls | [get_class_from_annotation(a)]
    end
    # logger.debug("P SENTENCE #{p.sentences.size}")
    p.sentences.each do |s|
      # logger.debug("S ANNNOTATION #{s.annotations.size}")
      s.annotations.each do |a|
        cls = cls | [get_class_from_annotation(a)]
        # logger.debug("Annotation Type #{cls.inspect}")
      end
    end
    # logger.debug("Annotation Type #{cls.inspect}")

    return cls.uniq
  end

  def get_class_from_annotation(a)
    type = a.infons['type']
    cls_name = case type.downcase
    when 'gene'
      "G"
    when 'organism'
      "O"
    when 'ppimention','ppievidence'
      "EP"
    when 'geneticinteractiontype', 'gievidence', 'gimention'
      "EG"
    when 'experimentalmethod'
      "EM"
    when 'none'
      ""
    else
      "E"
    end unless type.nil?

    return cls_name
  end

  def bioc
    if @bioc.nil?
      @bioc = SimpleBioC.from_xml_string(self.xml)
    end
    @bioc
  end

  def validate_xml
  end

  def overwrite_xml
    self.bioc.source = self.source
    self.bioc.date = self.d_date
    self.bioc.key = self.key
    self.bioc.documents[0].id = self.doc_id
    self.xml = SimpleBioC::to_xml(self.bioc)
  end

  def bioc_doc
    self.bioc.documents[0]
  end

  def verify
    result = []
    id_map = {}

    doc = self.bioc_doc
    doc.passages.each do |p|
      p.sentences.each do |s|
        check_duplicated_id(s.annotations, result, 'annotation', id_map)
        check_duplicated_id(s.relations, result, 'annotation', id_map)
      end
      check_duplicated_id(p.annotations, result, 'annotation', id_map)
      check_duplicated_id(p.relations, result, 'annotation', id_map)
    end
    doc.passages.each do |p|
      p.sentences.each do |s|
        check_annotation_location(s, result)
        check_relation_ref(s, result, id_map)
      end
      check_annotation_location(p, result)
      check_relation_ref(p, result, id_map)
    end

    result
  end

  def check_duplicated_id(coll, result, type, id_map)
    coll.each do |n|
      if id_map[n.id].nil?
        id_map[n.id] = 1
      else
        result << "#{n.id}: this #{type} ID is duplicated"
      end
    end
  end

  def check_annotation_location(obj, result)
    misaligned = adjust_annotation_offsets(obj, true)
    misaligned.each do |item|
      result << "The annotation #{item[0]} is misaligned [#{item[1]}:#{item[2]}] (auto-fixed to [#{item[3]}:#{item[2]}])"
    end
    obj.annotations.each do |a|
      a.locations.each do |l|
        start_pos = l.offset.to_i - obj.offset
        end_pos = start_pos + l.length.to_i
        text = obj.text[start_pos...end_pos]
        if text != a.text
          result <<  "The annotation #{a.id} is misaligned [#{l.offset}:#{l.length}] (the text in annotation '<b>#{a.text}</b>' is different from the one at the location '<b>#{text}</b>')"
        end
      end
    end
  end

  def check_relation_ref(obj, result, id_map) 
    obj.relations.each do |r|
      r.nodes.each do |n|
        if id_map[n.refid].nil?
          result << "The relation #{r.id} refers non-existing nodes (refid: #{n.refid})"
        end
      end
    end
  end

  def adjust_offset(needFix)
    doc = self.bioc_doc
    doc.passages.each do |p|
      adjust_annotation_offsets(p, needFix)
      p.sentences.each do |s|
        adjust_annotation_offsets(s, needFix)
      end
    end
  end

  def adjust_annotation_offsets(obj, needFix)
    return if obj.nil? || obj.annotations.nil?
    ret = []
    obj.annotations.each do |a|
      positions = find_all_locations(obj, a.text)
      next if a.locations.nil?
      a.locations.each do |l|
        next if l.nil? || l == false
        candidate = choose_offset_candidate(l.offset, positions)
        if candidate.to_i != l.offset.to_i
          val = a.infons["error:misaligned:#{a.id}"] || ""
          arr = val.split(",")
          arr << "#{l.offset}->#{candidate}"
          a.infons["error:misaligned:#{a.id}"] = arr.join(",")
          ret << [a.id, l.offset, l.length, candidate]
          if needFix
            l.offset = candidate
          end
        end
      end
    end
    return ret
  end

  def find_all_locations(obj, text)
    positions = []
    return positions if obj.nil? || obj.text.nil?
    pos = obj.text.index(text)
    until pos.nil? 
      positions << (pos + obj.offset)
      pos = obj.text.index(text, pos + 1)
    end
    return positions
  end

  def choose_offset_candidate(offset, positions)
    return offset if positions.nil?
    min_diff = 99999
    offset = offset.to_i
    ret = offset
    positions.each do |p|
      diff = (offset - p).abs
      if diff < min_diff
        ret = p 
        min_diff = diff
      end
    end
    return ret
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy, :merge, :verify]
  before_action :authenticate_user!
  
  # GET /documents
  # GET /documents.json
  def index
    unless current_user.super_admin?
      redirect_to "/", error: "Cannot access the document"
    end

    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @project = @document.project
    @document.adjust_atypes
    @document.adjust_offset(true)
    unless @project.readable?(current_user)
      redirect_to "/", error: "Cannot access the document"
    end
    respond_to do |format|
      format.html
      format.json
      format.xml {render xml: @document.xml}
    end
  end

  def verify
    @project = @document.project
    render json: @document.verify
  end
  
  # GET /documents/new
  def new
    @project = Project.find(params[:project_id])
    unless @project.admin?(current_user)
      redirect_to "/", error: "Cannot access the document"
    end
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
    @project = @document.project
    unless @project.admin?(current_user)
      redirect_to "/", error: "Cannot access the document"
    end
  end

  # POST /documents
  # POST /documents.json
  def create
    @project = Project.find(params[:project_id])

    unless @project.admin?(current_user)
      redirect_to "/", error: "Cannot access the document"
    end
    @document = Document.create_from_file(params[:file])
    if @document.nil?
      respond_to do |format|
        format.html { render status: :unprocessable_entity, text: "Invalid document by BioC DTD"}
      end
      return 
    end
    @document.project_id = @project.id
    @document.user_id = current_user.id

    respond_to do |format|
      if @document.save
        format.html { redirect_to @project, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    @project = @document.project
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @project, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @project = Project.find(params[:project_id])
    unless @project.admin?(current_user)
      redirect_to "/", error: "Cannot access the document"
    end

    return_url = if @project.present? then url_for(@project) else documents_url end
    @document.destroy
    respond_to do |format|
      format.html { redirect_to return_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def merge
    @project = @document.project
    unless @project.admin?(current_user)
      redirect_to "/", error: "Cannot access the document"
    end
   
    @dest = Document.find(params[:with])
    @document.merge_with(@dest)
    @document.adjust_offset(true)
    unless params[:nodelete]
      @dest.destroy
    end
    # logger.debug(params[:files].inspect)
    # errors = []
    # @document = Document.merge_documents(@project, current_user, params[:files], errors)
    # if @document.nil?
    #   respond_to do |format|
    #     format.html { redirect_to @project, error: errors.join(",")}
    #   end
    #   return 
    # end

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Merged document was successfully created.' }
        format.json { render json: {code: "ok"}, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:file, :doc_id, :d_date, :key, :source, :filename)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_annotations.html.erb
  <div class="ui very close rail right annotations">
    <div class="ui segment">
      <span class="ui right ribbon label">Annotations 
        (<%=annotations.size %>)
      </span>
      <ul class="ui list body">
        <% annotations.each do |a| %>
          <li class="annotation-item">
            <%=a.id %>
            <% type = a.infons['type'] %>

            <% unless type.nil? %>
              <span class='ui label mini <%=Document::TYPE2COLOR[type.downcase]%>'><%=type%></span>
              <% case type.downcase %>
              <% when 'gene' %>
                <% tid = a.infons['GeneID'] %>
                <a href='http://www.ncbi.nlm.nih.gov/gene?term=<%=tid%>' target='_blank'><i class='icon globe'></i><%=tid%></a>
              <% when 'organism' %>
                <% tid = a.infons['OrganismID'] %>
                <a href='http://www.ncbi.nlm.nih.gov/bioproject?term=txid<%=tid%>%5Borgn%5D' target='_blank'><i class='icon globe'></i><%=tid%></a>
              <% else %>
              <% end %>
            <% end %>
            <div class="locations">
              <% a.locations.each do |l| %>
                <span class="label mini ui"><%=l.offset%>:<%=l.length%></span>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

app/views/documents/_buttons.html.erb
<div class="fixed-buttons">
  <%= link_to @document.project, class: "ui button small" do %>
    <i class="icon chevron left"></i> Back to Project
  <% end %>
  <button class="ui button small doc-info-btn" type="button">
    <i class="icon info circle"></i> Doc Info
  </button>
  <%= link_to "/documents/#{@document.id}.xml", class: 'ui button teal small' do %>
    <i class='icon download'></i> BioC 
  <% end %>
  <div class='error-checker'>
    <div class='ui active small inverted inline loader'></div>
    <button class="ui button small yellow btn-errors">
      <i class='icon warning sign'></i> 
      Error
    </button>
    <div class="ui button small green">
      <i class='icon checkmark'></i> 
      No error
    </div>
  </div>
  <div class="ui teal buttons small annotation-toggles">
    <div class="ui button small">Annotation Types</div>
    <div class="ui floating dropdown icon button small">
      <i class="dropdown icon"></i>
      <div class="menu" style='z-index:9999'>
        <div class="header">
          <i class="setting icon"></i>
          <%=link_to 'Settings', document_atypes_path(@document) %>
        </div>
        <div class="divider"></div>
        <% if @document.atypes.blank? %>
          <div class="item">
            <label>No annotation type found</label>
          </div>
        <% end %>
        <% @document.atypes.each do |type| %>
          <div class="item" data-type='A<%=type.id%>'>
            <div class="ui checkbox">
              <input type="checkbox" class="atype-check" checked>
              <label><div class="ui A<%=type.id%> empty circular <%='thin' if type.border? %> label" data-type='A<%=type.id%>'></div>
            <%=type.name %></label>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</div>
<style type='text/css'>
  <% @document.atypes.each do |type| %>
    .ui.A<%=type.id%>.empty.label.circular {
      <% if type.border? %>
        border: 0.2em solid <%=type.color%> !important;
        width: 1em;
        height: 1em;
        box-sizing: border-box;
        padding: 0 !important;
      <% else %>
        background-color: <%=type.color%> !important;
      <% end %>

    }
  <% end %>
</style>
<script>
  $('.atype-check').change(function(e) {
    var $e = $(e.currentTarget);
    var type = $e.closest('.item').data('type');
    $('.main.pane').toggleClass(type + '-enabled', $e.prop('checked'));
  });
</script>

app/views/documents/_delete_confirm_modal.html.erb
<div class="ui small basic modal delete-confirm" >
  <i class="close icon"></i>
  <div class="header">
    Are you sure for delete?
  </div>
  <div class="actions">
      <div class="ui red deny inverted button" data-value='ppi'>
        <i class="remove icon"></i>
        No
      </div>
      <div class="ui green approve inverted button" data-value='gi'>
        <i class="checkmark icon"></i>
        Yes
      </div>
  </div>
</div>

app/views/documents/_errors_modal.html.erb
<div class="ui modal error-modal" >
  <i class="close icon"></i>
  <div class="header">
    <i class="large warning sign icon"></i>
    Errors
  </div>
  <div class="content">
    <ol>
    </ol>
  </div>
</div>

app/views/documents/_infon.html.erb
<div class="ui modal <%=cls_name%>">
  <i class="close icon"></i>
  <div class="header">
    Infon (<%=infons.size %>)
  </div>
  <div class="content">
    <ul class="ui list body">
      <% infons.each do |key, value| %>
        <li>
          <%=key %>: <%= value %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/documents/edit.html.erb
<h1 class='ui dividing header'>
  <div class='content'>Editing Document Information</div>
</h1>

<%= render 'form' %>
<div class='ui divider'></div>
<%= link_to 'Show', @document %> |
<%= link_to 'Back', @project %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Documents</h1>

<table>
  <thead>
    <tr>
      <th>Version</th>
      <th>User</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.version %></td>
        <td><%= document.user %></td>
        <td><%= document.project %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1 class="ui dividing header">New Document</h1>

<%= render 'form' %>


<div class="ui divider"></div>
<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<%= render partial: "buttons" %>
<style type='text/css'>
  <% enabled = [] %>
  <% @document.atypes.each do |type| %>
    .A<%=type.id%>-enabled span.annotation.A<%=type.id%> {
      <% if type.border? %>
        border-bottom: 3px solid <%=type.color%> !important;
      <% else %>
        background-color: <%=type.color%> !important;
      <% end %>
    }

    .A<%=type.id%>-disabled span.annotation.A<%=type.id%> {
      <% if type.border? %>
        border: 3px solid transparent;
      <% else %>
        background-color: transparent;
      <% end %>      
    }
    <% enabled << "A#{type.id}-enabled" %>
  <% end %>
</style>
<div class="ui dimmer" id="documentSpinner">
  <div class="ui text loader">Loading</div>
</div>
<%= render partial: "doc_info" %>
<div class="document clearfix <%=@project.mode%>">
  <div class="left-side pane">
    <h4>Outline</h4>
    <%= render partial: "outline", locals: {nodes: @document.outline} %>
  </div>
  <div class="main pane <%=enabled.join(' ')%>" id="main-document">
    <% @document.bioc_doc.passages.each_with_index do |p, index| %>
      <div class="ui basic segment passage" data-id="<%=index%>" id="passage-<%=index%>" >
        <div class="ui top right attached label mini passage-sub-info">
          offset: <%=p.offset%> - <%=p.offset + @document.get_psize(p)%>
        </div>
        <%=render partial: "infon", locals: {infons: p.infons, cls_name: "infon-#{index}"} %>
        <a href="#" class="infon-btn ui top left attached label mini passage-sub-info" data-id="<%=index%>">
          <%=p.infons["type"]%> <div class="detail">
          <i class="icon info circle"></i><%=p.infons.size%></div>
        </a>
        <% case p.infons["type"] %>
        <% when "ref" %>
          <%=render partial: "ref", locals: {infons: p.infons, title: p.text} %>
        <% when "front" %>
          <% if p.text.blank? %>
            <h1 class="<%=p.infons["type"]%>"><%-
              p.sentences.each do |s|
                -%><%=render partial: "text_fragment", locals: {p: s, ptext: s.text}%><%-
              end
              -%></h1>
          <% else %>
            <h1 class="<%=p.infons["type"]%>"><%=render partial: "text_fragment", locals: {p: p, ptext: p.text}%></h1>
          <% end %>
          <div class="ui message">
            <%=render partial: "ref", locals: {infons: p.infons, title: nil} %>
          </div>
        <% else %>
            <% if p.text.blank? %>
              <div class="text <%=p.infons["type"]%>"><%-
                p.sentences.each do |s|
                  -%><%=render partial: "text_fragment", locals: {p: s, ptext: s.text}%><%-
                end
                -%></div>
            <% else %>
              <div class="text <%=p.infons["type"]%>"><%=render partial: "text_fragment", locals: {p: p, ptext: p.text}%></div>
            <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="ui right top right-side pane <%='readonly' unless @document.project.writable?(current_user)%>" style='display:none'>
    <% if @document.project.mode == "BioGrid" %>
      <% if @document.project.writable?(current_user) %>
        <%= render partial: "ppi_form" %>
        <% end%>
      <div class="ppis">
        <h4>
          PPI/GI List 
          <span class="ui label circular olive ppi-cnt tiny"></span>
          <div class="export-btn-section">
            <%=link_to "/documents/#{@document.id}/ppis.csv", class: "export-btn ui teal circular icon button small", title: "Export to CSV", target: "_blank" do %>
              <i class="icon download"></i> CSV
            <% end %>
            <%=link_to "/documents/#{@document.id}/ppis.xls", class: "export-btn ui teal circular icon button small", title: "Export to XLS", target: "_blank" do %>
              <i class="icon download"></i> XLS
            <% end %>
          </div>
        </h4>
        <table class="ui small table celled blue very compact">
          <thead>
            <th></th>
            <th>Gene 1</th>
            <th>Gene 2</th>
            <% if @document.project.writable?(current_user) %>
              <th></th>
            <% end %>
          </thead>
          <tbody class="ppi-list">
          </tbody>
        </table>
      </div>
    <% else %>
    <% end %>
  </div>
</div>
<%=render partial: "errors_modal" %>

<% if @document.project.mode == "BioGrid" %>
  <%=render partial: "ppi_type_modal" %>
  <%=render partial: "ppi_exp_modal" %>
  <%=render partial: "delete_confirm_modal" %>
  <script id="ppi-template" type="text/x-handlebars-template">
    <tr data-id="{{id}}" class="{{toUpperCase itype}} item">
      <td class="type type-toggle" rowspan="2">
        <div class="PPI">PPI</div>
        <div class="GI">GI</div>
      </div>
      <td class='gene'>
        <a href='http://www.ncbi.nlm.nih.gov/gene?term={{gene1}}' target='_blank'><i class='icon globe'></i>{{gene1}}</a>
        <br>
        <span class='popup' title='{{name1}}'>{{name1}}</span>
        <div class='ui popup' style='display:none'>{{name1}}</div>
      </td>
      <td class='gene'>
        <a href='http://www.ncbi.nlm.nih.gov/gene?term={{gene2}}' target='_blank'><i class='icon globe'></i>{{gene2}}</a>
        <br>
        <span class='popup' title='{{name2}}'>{{name2}}</span>
        <div class='ui popup' style='display:none'>{{name2}}</div>
      </td>
      <% if @document.project.writable?(current_user) %>
        <td class='action' rowspan="2">
          <a class="delete-button" rel="nofollow" href="#" title="Delete">
            <i class="delete icon"></i>
          </a>
        </td>
      <% end %>
    </tr>
    <tr data-id="{{id}}" class="item">
      <td colspan="2" class="exp-name">
        <span>{{exp}}</span>
        <% if @document.project.writable?(current_user) %>
          <a class="edit-button" rel="nofollow" href="#" title="Edit">
            <i class="write icon"></i>
          </a>
        <% end %>
      </td>
    </tr>
  </script>
<% end %>
<script>
setTimeout(function() {
  $('.error-checker').addClass('loading');
  $.getJSON("/documents/<%=@document.id%>/verify", function(data) {
    $('.error-checker').removeClass('loading');
    if (data.length > 0) {
      $('.error-checker').addClass('error');
      var items = _.map(data, function(str) {
        return "<li>" + str + "</li>";
      });
      $('.error-modal .content ol').html(items.join('\n'));
    } else {
      /*$('.error-checker').addClass('no-error');*/
    }
  });
}, 0);
$('.btn-errors').click(function() {
  $('.error-modal').modal('show');
});
$(function() {
  var doc = new BioC('<%=@document.id%>', {
    root: '<%=root_path%>',
    mode: '<%=@document.project.mode %>',
    isReadOnly: '<%='true' unless @document.project.writable?(current_user)%>',
    ppiArray: [
     <% @document.ppis.each do |p| %>
        {
          id: <%=p.id%>,
          document_id: <%=p.document_id %>,
          itype: '<%=p.itype %>',
          exp: '<%=p.exp %>',
          gene1: '<%=p.gene1 %>',
          name1: '<%=p.name1 %>',
          gene2: '<%=p.gene2 %>',
          name2: '<%=p.name2 %>',
          url: '<%=ppi_url(p, format: :json) %>'
        },
      <% end %>
    ]
  });
  $("#documentSpinner").removeClass("active");
});
</script>