config/routes.rb
Rails.application.routes.draw do
    
  resources :atypes
  resources :ppis

  authenticated :user do  
    root 'projects#index'   
  end   
    
  unauthenticated do    
    root 'home#index', :as => "unauthenticated"   
  end 
  resources :temp_documents

  resources :revisions

  resources :documents do
    member do
      post 'merge'
      get 'verify'
    end
    resources :ppis
    resources :atypes
  end

  resources :project_users

  resources :projects do 
    resources :documents do
    end
    member do 
      get 'check_same_documents'
    end
    resources :project_users
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'home/index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :owner, class_name: "User", foreign_key: 'user_id'
  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users
  has_many :documents, dependent: :destroy
  
  validates :title, presence: true
  validates :user_id, presence: true

  after_create :add_owner_to_users

  def add_owner_to_users
    self.project_users.create({user_id: self.user_id, priv: "rwa"})
  end

  def get_documents(source, doc_id, key, d_date)
    rows = self.documents.where(["source = ? and doc_id = ? and `key` = ? and d_date = ?", 
        source, doc_id, key, d_date]).select("id")
    rows.map{|r| r.id}
  end

  def owner?(user)
    self.owner.id == user.id
  end

  def readable?(user)
    pu = self.project_users.where("user_id = ?", user.id).first
    !pu.nil? && pu.readable?
  end

  def writable?(user)
    pu = self.project_users.where("user_id = ?", user.id).first
    !pu.nil? && pu.writable?
  end

  def admin?(user)
    pu = self.project_users.where("user_id = ?", user.id).first
    !pu.nil? && pu.admin?
  end

  def priv
    pu = self.project_users.where("user_id = ?", user.id).first
    if pu.nil?
      ""
    else
      pu.priv
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :check_same_documents]
  before_action :authenticate_user!
  
  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects.all

    logger.debug("ALLOWED? #{current_user.email} #{allowed_user?}")
    # unless allowed_user?
    #   render 'home/index', notice: 'BioC-Viewer is not available for service upgrade.'
    # end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    unless @project.readable?(current_user)
      redirect_to "/", error: "Cannot access the project"
    end
    @documents = @project.documents.order("id ASC").page(params[:page]).per(10)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    unless @project.admin?(current_user)
      redirect_to "/", error: "Cannot access the project"
    end
  end

  def check_same_documents
    @rows = Document.find_by_sql(["
      select source, d_date, `key`, doc_id, count(*) as cnt from documents
      where project_id = ? and source is not null and `key` is not null and doc_id is not null and d_date is not null
      group by source, d_date, `key`, doc_id
      having cnt >= 2
      order by source, d_date, `key`, doc_id", params[:id]])
    respond_to do |format|
      format.json {render :check_same_documents}
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    unless @project.admin?(current_user)
      redirect_to "/", error: "Cannot access the project"
    end
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    unless @project.admin?(current_user)
      redirect_to "/", error: "Cannot access the project"
    end

    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :user_id, :description, :mode)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project, html: {class: "ui form"}) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :mode %>
    <div class="ui radio checkbox" style='margin-right: 2em;'>
      <%= f.radio_button(:mode, 'Normal') %>
      <label>Normal</label>
    </div>
    <div class="ui radio checkbox">
      <%= f.radio_button(:mode, 'BioGrid') %>
      <label>BioGRID: PPI/GI curation tool is visible. This tool can be used for PPI/GI curation for BioGRID</label>
    </div>
    
  </div>

  <div class="actions">
    <% if params[:action] == 'new' %>
      <%= link_to 'Back', projects_path, class: "ui button" %>
    <% else %>
      <%= link_to 'Back', @project, class: "ui button" %>
    <% end %>
    <%= f.submit  class: "ui primary button" %>
  </div>
<% end %>

<script>
$(function() {
  $('select.dropdown').dropdown();
});
</script>

app/views/projects/_merge_documents_modal.html.erb
<div class="ui modal merge-dialog">
  <i class="close icon"></i>
  <div class="header">
    <div class="header">Merge files</div>
  </div>
  <div class="content">
    <div class='info'>
    </div>
    <div id="mergeProgress" class="ui progress blue">
      <div class="bar">
        <div class="progress"></div>
      </div>
      <div class="label">Ready to upload</div>
    </div>
    <div id="mergeError" style="display:none" class="ui icon message error">
      <i class="icon warning sign"></i>
      <div class="content">
        <div class="header">
          Sorry. Please try again later.
        </div>
        <p class='message'>

        </p>
      </div>
    </div>
  </div>
  <div class="actions">
    <button class='ui button blue btn-start-merge'>Start</button>
    <div class="ui cancel button btn-close-merge">
      Close
    </div>
  </div>
  </form>
</div>
<script>
var mergeIdx = 0;
var mergeDocs = [];
var mergeUrl = "";
function postMerge(data) {
  $('#mergeProgress').progress('increment');
  mergeIdx++;
  var doc = mergeDocs[mergeIdx];
  if (doc !== undefined) {
    $.ajax({
      method: 'POST',
      url: mergeUrl, 
      data: {with: doc}, 
      success: function(data) {
        $("#mergeError").hide();
        postMerge(data);
      }, 
      error: function(xhr, status, error) {
        $("#mergeError p").html((xhr.status || status) + " : " + error);
        $("#mergeError").show();
      }
    });
  } else {
    $('.btn-close-merge').text('Done').removeClass('disabled').addClass('blue');
    $('.btn-start-merge').hide();
  }
}

$('.btn-start-merge').click(function() {
  mergeDocs = $('.merge-dialog .doc-for-merge').data("doc").split(",");
  mergeIdx = 0;
  mergeUrl = "/documents/" + mergeDocs[0] + "/merge.json";
  $('.btn-start-merge').addClass('disabled');
  $('.btn-close-merge').addClass('disabled');

  $('.merge-dialog').modal({
    onHidden: function() {
      $('#reloadSpinner').addClass('active');
      location.reload();
    }
  });
  postMerge();
});
</script>

app/views/projects/edit.html.erb
<h1 class="ui dividing header">Editing Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1 class="ui dividing header">Projects</h1>

<table  class="ui table celled striped ">
  <thead>
    <tr>
      <th>Title</th>
      <th>Mode</th>
      <th># Documents</th>
      <th>Owner</th>
      <th># Users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%=link_to project.title, project %></td>
        <td><%= project.mode %></td>
        <td><%= project.documents.size %></td>
        <td><%= project.owner.name %></td>
        <td><%= project.users.size %></td>
        <td>
          <div class="ui right pointing dropdown">
            <i class="setting icon blue"></i>
            <div class="menu">
              <div class="item">
                <%= link_to project_project_users_path(project) do %>
                  <i class="icon users"></i> Manage Users
                <% end %>
              </div>
              <div class="ui divider"></div>
              <div class="item">
                <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="delete icon"></i> Remove
                <% end %>
              </div>
            </div>
          </div>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_project_path, class: "ui primary button" do %>
  <i class="icon add"></i> New Project
<% end %>
<a href="/10366597.xml" style="margin-top: -1em; margin-bottom: 2em; display: block; width: 100%; text-align: right;">
  <i class="icon download"></i> Download a sample BioC document
</a> 

app/views/projects/new.html.erb
<h1 class="ui dividing header">New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1 class="ui dividing header">
  <%= @project.title %>
  <div class="sub header"><%= @project.mode %> Project</div>
</h1>

<ul class="ui bulleted list">
  <li class="item">
    <strong>Owner:</strong>
    <%= @project.owner.name %>
  </li>
  <% unless @project.description.blank? %>
    <li class="item">
      <strong>Description:</strong>
      <%=simple_format @project.description %>
    </li>
  <% end %>
</ul>

<div class="page-info">
  Total <b><%=@documents.total_count %></b> documents
  <% unless @documents.empty? %>
    (<b><%=@documents.current_page %></b> of <b><%=@documents.total_pages %></b> pages)
  <% end %>
</div>
<% if @documents.empty? %>
  <div class="ui message info">
    No document yet. Please upload documents first.
  </div>

<% else %>
  <table class="ui table celled striped ">
    <thead>
      <tr>
        <th>Doc ID</th>
        <th>Original Filename</th>
        <th>Source</th>
        <th>Date</th>
        <th>Key</th>
        <% if @project.mode == "BioGrid" %>
          <th># Interactions</th>
        <% end %>
        <th>Created At</th>
        <th></th>
      </tr>
    </thead>
    <% @documents.each do |d| %>
      <tr>
        <td><%=link_to d.doc_id, d %></td>
        <td><%= d.filename %></td>
        <td><%= d.source %></td>
        <td><%= d.d_date %></td>
        <td><%= d.key %></td>
        <% if @project.mode == "BioGrid" %>
          <td><%= d.ppis.size %></td>
        <% end %>
        <td><%=time_ago_in_words d.created_at %> ago </td>
        <td>
          <div class="ui right pointing dropdown">
            <i class="setting icon blue"></i>
            <div class="menu">
              <div class="item">
                <%=link_to "/documents/#{d.id}.xml", target: "_blank" do %>
                  <i class="icon file"></i> Download BioC
                <% end %>
              </div>
              <div class="item">
                <%=link_to "/documents/#{d.id}/edit" do %>
                  <i class="icon pencil"></i> Edit Document Info.
                <% end %>
              </div>
              <% if @project.mode == "BioGrid" %>
                <div class="ui divider"></div>
                <div class="item">
                  <%=link_to "/documents/#{d.id}/ppis.csv", target: "_blank" do %>
                    <i class="icon download"></i> Export Interactions to CSV
                  <% end %>
                </div>
                <div class="item">
                  <%=link_to "/documents/#{d.id}/ppis.xls", target: "_blank" do %>
                    <i class="icon download"></i> Export Interactions to XLS
                  <% end %>
                </div>
              <% end %>
              <% if @project.admin?(current_user) %>
                <div class="ui divider"></div>
                <div class="item">
                  <%= link_to [@project, d], method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="delete icon"></i> Remove
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
  <div class="pagination-section">
    <%= paginate @documents %>
  </div>
<% end %>
<% if @project.admin?(current_user) %>
  <div class="ui dimmer" id="uploadSpinner">
    <div class="ui text loader">Uploading</div>
  </div>
  <div id="fileuploader">Upload BioC Documents</div>
  <a href="/10366597.xml" style="margin-top: -1em; margin-bottom: 2em; display: block; width: 100%; text-align: right;">
    <i class="icon download"></i> Download a sample BioC document
  </a> 
  <div class='ui message blue merge-recommender'>
    <div class="ui dimmer" id="reloadSpinner">
      <div class="ui text loader">Reloading</div>
    </div>
    <div class='header'>
      Found documents that could be merged
    </div>
    <table class='ui small compact selectable inverted teal table'>
      <thead>
        <tr>
          <th>Doc ID</th>
          <th>Source</th>
          <th>Key</th>
          <th>Date</th>
          <th># Documents</th>
          <th></th>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
<% end %>

<div class="ui divider"></div>

<%= link_to projects_path , class: "ui button" do %>
  <i class="icon angle left"></i> Back
<% end %>
<% if @project.admin?(current_user) %>
  <%= link_to edit_project_path(@project), class: "ui button" do %>
    <i class="icon setting"></i> Project Settings
  <% end %>
  <%= link_to project_project_users_path(@project), class: "ui button teal" do %>
    <i class="icon users"></i> Manage Users
  <% end %>
  <%= link_to @project, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui button red" do %>
    <i class="icon trash"></i> Remove Project
  <% end %>
<% end %>
<%=render partial: 'merge_documents_modal' %>
<script id="merge-row-template" type="text/x-handlebars-template">
  <tr data-source="{{source}}" data-id="{{doc_id}}" data-doc="{{documents}}" 
      data-key="{{key}}" data-date="{{d_date}}">
    <td>{{doc_id}}</td>
    <td>{{source}}</td>
    <td>{{key}}</td>
    <td>{{d_date}}</td>
    <td>{{cnt}}</td>
    <td><button class='ui button olive mini btn-merge'>Merge</button></td>
  </tr>
</script>
<script id="merge-dialog-template" type="text/x-handlebars-template">
  <h3>{{cnt}} files to be merged</h3>
  <ul class="doc-for-merge" data-doc="{{documents}}">
    <li>ID: {{id}}</li>
    <li>Source: {{source}}</li>
    <li>Key: {{key}}</li>
    <li>Date: {{date}}</li>
  </ul>
</script>

<script>
$(function() {
  var mergeTemplate = Handlebars.compile($("#merge-row-template").html())
  var mergeDialogTemplate = Handlebars.compile($("#merge-dialog-template").html())

  $("#fileuploader").uploadFile({
    url: "/projects/<%=@project.id%>/documents",
    fileName: "file",
    sequential: true,
    sequentialCount: 1,
    dragdropWidth: '100%',
    allowedTypes: 'xml',
    uploadStr: 'Upload Multiple BioC Documents',
    afterUploadAll: function(obj) {
      console.log(obj);
      location.reload();
    },
    onError: function(files,status,errMsg,pd) {
      //files: list of files
      //status: error status
      //errMsg: error message
      if (errMsg === 'Unprocessable Entity') {
        toastr.error(files[0] + ": Invalid document to BioC DTD", null,{
          positionClass: "toast-bottom-full-width"
        });
      } else {
        toastr.error(errMsg);
      }
      // location.reload();
    }, 
    onSuccess:function(files,data,xhr,pd) {
      //files: list of files
      //data: response from server
      //xhr : jquer xhr object
      toastr.success(files + " files were uploaded successfully.", null,{
        positionClass: "toast-bottom-full-width"
      });
      
    }

  });

  $("#hiddenFileInput").change(function() {
    $("#uploadSpinner").addClass("active");
    $("#uploadForm").submit();
  });

  $("#uploadBtn").click(function() {
    $("#hiddenFileInput").click();
  });
<% if @project.admin?(current_user) %>
  $.getJSON("<%=url_for check_same_documents_project_path(@project)%>", function(data) {
    if (data && data.length > 0) {
      _.each(data, function(item) {
        $('.merge-recommender table tbody').append(mergeTemplate(item));
      });
      $('.merge-recommender').addClass('has-same');

      $('.btn-merge').click(function(e) {
        var $tr = $(e.currentTarget).closest('tr');
        var documents = $tr.data('doc').split(',');
        var item = {
          source: $tr.data('source'),
          id: $tr.data('id'),
          date: $tr.data('date'),
          key: $tr.data('key'),
          cnt: documents.length,
          documents: documents
        };
        $("#mergeError").hide();
        $('.merge-dialog .info').html(mergeDialogTemplate(item));
        $('#mergeProgress').progress({
          value: 0, 
          total: documents.length,
          text: {
            active  : 'Merging {value} of {total} files',
            success : '{total} files merged!'
          }
        });
        $('.merge-dialog').modal({
          blurring: true
        })
        .modal('show');
      });
    }
  });
<% end %>
});
</script>