config/routes.rb
Rails.application.routes.draw do
    
  resources :atypes
  resources :ppis

  authenticated :user do  
    root 'projects#index'   
  end   
    
  unauthenticated do    
    root 'home#index', :as => "unauthenticated"   
  end 
  resources :temp_documents

  resources :revisions

  resources :documents do
    member do
      post 'merge'
      get 'verify'
    end
    resources :ppis
    resources :atypes
  end

  resources :project_users

  resources :projects do 
    resources :documents do
    end
    member do 
      get 'check_same_documents'
    end
    resources :project_users
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'home/index'

end

app/models/project_user.rb
class ProjectUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :user_id, presence: {
    message: "does not exist."
  }
  validates :user_id, uniqueness: { scope: :project_id,
    message: "already joined this project." }
  validates :project_id, presence: true
  validates :priv, length: { minimum: 1, 
      too_short: "shoud not be empty."
   }
  def readable?
    self.priv.downcase.include?("r")
  end

  def writable?
    self.priv.downcase.include?("w")
  end

  def admin?
    self.priv.downcase.include?("a")
  end
end

app/controllers/project_users_controller.rb
class ProjectUsersController < ApplicationController
  before_action :set_project_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /project_users
  # GET /project_users.json
  def index
    @project = Project.where("id=?", params[:project_id]).first
    if @project.nil?
      redirect_to "/", error: 'Not exist project'
      return
    else
      @project_users = @project.project_users
    end
  end

  # GET /project_users/1
  # GET /project_users/1.json
  def show
  end

  # GET /project_users/new
  def new
    @project = Project.find(params[:project_id])
    @project_user = ProjectUser.new
  end

  # GET /project_users/1/edit
  def edit
    @project = Project.find(params[:project_id])
  end

  # POST /project_users
  # POST /project_users.json
  def create
    @project = Project.find(params[:project_id])
    @user = User.where("email = ?", params[:email]).first
    pu = ProjectUser.where("")
    privs = []
    privs << "r" if params[:r] == "1"
    privs << "w" if params[:w] == "1"
    privs << "a" if params[:a] == "1"
    @priv = privs.join("")
    @project_user = ProjectUser.new
    @project_user.project_id = @project.id
    @project_user.user_id = @user.id unless @user.nil?
    @project_user.priv = @priv

    # logger.debug("PRIV=#{@priv}, #{privs.inspect}")
    respond_to do |format|
      if @project_user.save
        format.html { redirect_to project_project_users_path(@project), notice: 'Project user was successfully created.' }
        format.json { render :show, status: :created, location: @project_user }
      else
        format.html { render :new }
        format.json { render json: @project_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_users/1
  # PATCH/PUT /project_users/1.json
  def update
    privs = []
    privs << "r" if params[:r] == "1"
    privs << "w" if params[:w] == "1"
    privs << "a" if params[:a] == "1"
    @priv = privs.join("")
    @project_user.priv = @priv
    @project = @project_user.project
    respond_to do |format|
      if @project_user.save
        format.html { redirect_to project_project_users_path(@project), notice: 'User setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_user }
      else
        format.html { render :edit }
        format.json { render json: @project_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_users/1
  # DELETE /project_users/1.json
  def destroy
    @project_user.destroy
    respond_to do |format|
      format.html { redirect_to project_users_url, notice: 'User setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_user
      @project_user = ProjectUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_user_params
      params.require(:project_user).permit(:email, :project_id, :r, :w, :a)
    end
end

app/helpers/project_users_helper.rb
module ProjectUsersHelper
  def ox_class(flag)
    if flag
      "green"
    else
      "grey disabled"
    end
  end

end

app/views/project_users/_form.html.erb
<%= form_for([@project, @project_user], html: {class: "ui form"}) do |f| %>
  <% if @project_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @project_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field <%='disabled' unless @project_user.user.nil? %>">
    <label>User Email</label>
    <% if @project_user.user.nil? %>
      <%= email_field_tag "email", '', placeholder: 'E-mail address (ex: john@test.com)' %>
    <% else %>
      <%= email_field_tag "email", @project_user.user.email, readonly: true, placeholder: 'E-mail address (ex: john@test.com)', class: "disbaled" %>
    <% end %>
  </div>
  <div class="field">
    <div class="ui checkbox">
      <input type="checkbox" value="1" name="r" <%='checked' if @project_user.readable? %> tabindex="0" class="hidden">
      <label>Read: able to read documents in this project</label>
    </div>
  </div>
  <div class="field">
    <div class="ui checkbox">
      <input type="checkbox" value="1" name="w" <%='checked' if @project_user.writable? %> tabindex="0" class="hidden">
      <label>Write: able to edit interactions in documents (only for BioGRID)</label>
    </div>
  </div>
  <div class="field">
    <div class="ui checkbox">
      <input type="checkbox" value="1" name="a" <%='checked' if @project_user.admin? %> tabindex="0" class="hidden">
      <label>Admin: able to add/remove documents/users in this project</label>
    </div>
  </div>

  <div class="actions">
    <%= link_to project_project_users_path(@project), class: "ui button" do %>
      <i class="icon angle left"></i> Back
    <% end %>
    <%= f.submit class: "ui button primary" %>
  </div>
<% end %>
<script>
$(function() {
  $('.ui.checkbox').checkbox();
});
</script>

app/views/project_users/edit.html.erb
<h1 class="ui dividing header">Editing Project User</h1>

<%= render 'form' %>

app/views/project_users/index.html.erb
<h1 class="ui dividing header">
  <%= @project.title %>
</h1>


<table class="ui table celled striped ">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Read</th>
      <th>Write</th>
      <th>Admin</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @project_users.each do |p| %>
      <tr>
        <td>
          <%= p.user.email %>
        </td>
        <td><%= p.user.name %></td>
        <td><i class='icon checkmark <%=ox_class(p.readable?)%>'></i></td>
        <td><i class='icon checkmark <%=ox_class(p.writable?)%>'></i></td>
        <td><i class='icon checkmark <%=ox_class(p.admin?)%>'></i></td>
        <td>
          <% if @project.owner?(p.user) %>
            <span class="ui green mini label">Owner</span>
          <% elsif @project.admin?(current_user)%>
            <div class="ui right pointing dropdown">
              <i class="setting icon blue"></i>
              <div class="menu">
                <div class="item">
                  <%= link_to edit_project_project_user_path(@project, p) do %>
                    <i class="icon setting"></i> Edit Privileges
                  <% end %>
                </div>
                <div class="ui divider"></div>
                <div class="item">
                  <%= link_to p, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="remove user icon"></i> Remove User
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to @project , class: "ui button" do %>
  <i class="icon angle left"></i> Back
<% end %>
<% if @project.admin?(current_user) %>
  <%= link_to new_project_project_user_path(@project), class: "ui button blue" do %>
    <i class="icon add user"></i> Add User
  <% end %>
<% end %>

app/views/project_users/new.html.erb
<h1 class="ui dividing header">New Project User</h1>

<%= render 'form' %>

app/views/project_users/show.html.erb
<p>
  <strong>User:</strong>
  <%= @project_user.user.name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @project_user.project %>
</p>

<p>
  <strong>Priv:</strong>
  <%= @project_user.priv %>
</p>

<%= link_to 'Edit', edit_project_user_path(@project_user) %> |
<%= link_to 'Back', project_users_path %>