config/routes.rb
Rails.application.routes.draw do
    
  resources :atypes
  resources :ppis

  authenticated :user do  
    root 'projects#index'   
  end   
    
  unauthenticated do    
    root 'home#index', :as => "unauthenticated"   
  end 
  resources :temp_documents

  resources :revisions

  resources :documents do
    member do
      post 'merge'
      get 'verify'
    end
    resources :ppis
    resources :atypes
  end

  resources :project_users

  resources :projects do 
    resources :documents do
    end
    member do 
      get 'check_same_documents'
    end
    resources :project_users
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'home/index'

end

app/models/temp_document.rb
class TempDocument < ActiveRecord::Base
end

app/controllers/temp_documents_controller.rb
class TempDocumentsController < ApplicationController
  before_action :set_temp_document, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /temp_documents
  # GET /temp_documents.json
  def index
    @temp_documents = TempDocument.all
  end

  # GET /temp_documents/1
  # GET /temp_documents/1.json
  def show
  end

  # GET /temp_documents/new
  def new
    @temp_document = TempDocument.new
  end

  # GET /temp_documents/1/edit
  def edit
  end

  # POST /temp_documents
  # POST /temp_documents.json
  def create
    @temp_document = TempDocument.new(temp_document_params)

    respond_to do |format|
      if @temp_document.save
        format.html { redirect_to @temp_document, notice: 'Temp document was successfully created.' }
        format.json { render :show, status: :created, location: @temp_document }
      else
        format.html { render :new }
        format.json { render json: @temp_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temp_documents/1
  # PATCH/PUT /temp_documents/1.json
  def update
    respond_to do |format|
      if @temp_document.update(temp_document_params)
        format.html { redirect_to @temp_document, notice: 'Temp document was successfully updated.' }
        format.json { render :show, status: :ok, location: @temp_document }
      else
        format.html { render :edit }
        format.json { render json: @temp_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temp_documents/1
  # DELETE /temp_documents/1.json
  def destroy
    @temp_document.destroy
    respond_to do |format|
      format.html { redirect_to temp_documents_url, notice: 'Temp document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temp_document
      @temp_document = TempDocument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temp_document_params
      params.require(:temp_document).permit(:user, :document, :xml)
    end
end

app/helpers/temp_documents_helper.rb
module TempDocumentsHelper
end

app/views/temp_documents/_form.html.erb
<%= form_for(@temp_document) do |f| %>
  <% if @temp_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temp_document.errors.count, "error") %> prohibited this temp_document from being saved:</h2>

      <ul>
      <% @temp_document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :document %><br>
    <%= f.text_field :document %>
  </div>
  <div class="field">
    <%= f.label :xml %><br>
    <%= f.text_area :xml %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temp_documents/edit.html.erb
<h1>Editing Temp Document</h1>

<%= render 'form' %>

<%= link_to 'Show', @temp_document %> |
<%= link_to 'Back', temp_documents_path %>

app/views/temp_documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Temp Documents</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Document</th>
      <th>Xml</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temp_documents.each do |temp_document| %>
      <tr>
        <td><%= temp_document.user %></td>
        <td><%= temp_document.document %></td>
        <td><%= temp_document.xml %></td>
        <td><%= link_to 'Show', temp_document %></td>
        <td><%= link_to 'Edit', edit_temp_document_path(temp_document) %></td>
        <td><%= link_to 'Destroy', temp_document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Temp document', new_temp_document_path %>

app/views/temp_documents/new.html.erb
<h1>New Temp Document</h1>

<%= render 'form' %>

<%= link_to 'Back', temp_documents_path %>

app/views/temp_documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @temp_document.user %>
</p>

<p>
  <strong>Document:</strong>
  <%= @temp_document.document %>
</p>

<p>
  <strong>Xml:</strong>
  <%= @temp_document.xml %>
</p>

<%= link_to 'Edit', edit_temp_document_path(@temp_document) %> |
<%= link_to 'Back', temp_documents_path %>